// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.3
// - protoc             (unknown)
// source: api/menu/menu.proto

package menu

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationMenuCreateSysMenu = "/atreus.menu.Menu/CreateSysMenu"
const OperationMenuGetMenu = "/atreus.menu.Menu/GetMenu"
const OperationMenuGrantList = "/atreus.menu.Menu/GrantList"
const OperationMenuListSysMenu = "/atreus.menu.Menu/ListSysMenu"

type MenuHTTPServer interface {
	CreateSysMenu(context.Context, *SysMenu) (*SysMenu, error)
	// GetMenu获取菜单树
	GetMenu(context.Context, *GetMenuReq) (*GetMenuResp, error)
	GrantList(context.Context, *emptypb.Empty) (*ListSysMenuResp, error)
	// ListSysMenu分页获取基础menu列表
	ListSysMenu(context.Context, *GetMenuReq) (*ListSysMenuResp, error)
}

func RegisterMenuHTTPServer(s *http.Server, srv MenuHTTPServer) {
	r := s.Route("/")
	r.POST("/system/menu/router", _Menu_GetMenu0_HTTP_Handler(srv))
	r.POST("/system/menu/list", _Menu_ListSysMenu0_HTTP_Handler(srv))
	r.POST("/system/menu/create", _Menu_CreateSysMenu0_HTTP_Handler(srv))
	r.GET("/system/menu/grant-list", _Menu_GrantList0_HTTP_Handler(srv))
}

func _Menu_GetMenu0_HTTP_Handler(srv MenuHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetMenuReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMenuGetMenu)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetMenu(ctx, req.(*GetMenuReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetMenuResp)
		return ctx.Result(200, reply)
	}
}

func _Menu_ListSysMenu0_HTTP_Handler(srv MenuHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetMenuReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMenuListSysMenu)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSysMenu(ctx, req.(*GetMenuReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSysMenuResp)
		return ctx.Result(200, reply)
	}
}

func _Menu_CreateSysMenu0_HTTP_Handler(srv MenuHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SysMenu
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMenuCreateSysMenu)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateSysMenu(ctx, req.(*SysMenu))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SysMenu)
		return ctx.Result(200, reply)
	}
}

func _Menu_GrantList0_HTTP_Handler(srv MenuHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMenuGrantList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GrantList(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSysMenuResp)
		return ctx.Result(200, reply)
	}
}

type MenuHTTPClient interface {
	CreateSysMenu(ctx context.Context, req *SysMenu, opts ...http.CallOption) (rsp *SysMenu, err error)
	GetMenu(ctx context.Context, req *GetMenuReq, opts ...http.CallOption) (rsp *GetMenuResp, err error)
	GrantList(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *ListSysMenuResp, err error)
	ListSysMenu(ctx context.Context, req *GetMenuReq, opts ...http.CallOption) (rsp *ListSysMenuResp, err error)
}

type MenuHTTPClientImpl struct {
	cc *http.Client
}

func NewMenuHTTPClient(client *http.Client) MenuHTTPClient {
	return &MenuHTTPClientImpl{client}
}

func (c *MenuHTTPClientImpl) CreateSysMenu(ctx context.Context, in *SysMenu, opts ...http.CallOption) (*SysMenu, error) {
	var out SysMenu
	pattern := "/system/menu/create"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMenuCreateSysMenu))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MenuHTTPClientImpl) GetMenu(ctx context.Context, in *GetMenuReq, opts ...http.CallOption) (*GetMenuResp, error) {
	var out GetMenuResp
	pattern := "/system/menu/router"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMenuGetMenu))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MenuHTTPClientImpl) GrantList(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*ListSysMenuResp, error) {
	var out ListSysMenuResp
	pattern := "/system/menu/grant-list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMenuGrantList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MenuHTTPClientImpl) ListSysMenu(ctx context.Context, in *GetMenuReq, opts ...http.CallOption) (*ListSysMenuResp, error) {
	var out ListSysMenuResp
	pattern := "/system/menu/list"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMenuListSysMenu))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
