// Code generated by protoc-gen-go-server. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v0.0.1
// source: api/dict/dict.proto

package dict

import (
	context "context"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = grpc.Version

type DictImpl struct {
	cc DictClient
}

func NewDictImpl(conn *grpc.ClientConn) *DictImpl {
	return &DictImpl{cc: NewDictClient(conn)}
}

func (c *DictImpl) DictData(ctx context.Context, in *DictDataReq) (*DictDataResp, error) {
	return c.cc.DictData(ctx, in)
}

func (c *DictImpl) DictValidHash(ctx context.Context, in *emptypb.Empty) (*ValidHashResp, error) {
	return c.cc.DictValidHash(ctx, in)
}

func (c *DictImpl) Create(ctx context.Context, in *SysDict) (*SysDict, error) {
	return c.cc.Create(ctx, in)
}

func (c *DictImpl) Update(ctx context.Context, in *SysDict) (*SysDict, error) {
	return c.cc.Update(ctx, in)
}

func (c *DictImpl) Delete(ctx context.Context, in *SysDict) (*SysDict, error) {
	return c.cc.Delete(ctx, in)
}

func (c *DictImpl) Get(ctx context.Context, in *SysDict) (*SysDict, error) {
	return c.cc.Get(ctx, in)
}

func (c *DictImpl) List(ctx context.Context, in *SysDict) (*ListSysDictResp, error) {
	return c.cc.List(ctx, in)
}
