// Code generated by protoc-gen-go-server. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v0.0.1
// source: api/role/role.proto

package role

import (
	context "context"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = grpc.Version

type RoleImpl struct {
	cc RoleClient
}

func NewRoleImpl(conn *grpc.ClientConn) *RoleImpl {
	return &RoleImpl{cc: NewRoleClient(conn)}
}

func (c *RoleImpl) CreateSysRole(ctx context.Context, in *SysRole) (*SysRole, error) {
	return c.cc.CreateSysRole(ctx, in)
}

func (c *RoleImpl) Update(ctx context.Context, in *SysRole) (*SysRole, error) {
	return c.cc.Update(ctx, in)
}

func (c *RoleImpl) Delete(ctx context.Context, in *SysRole) (*emptypb.Empty, error) {
	return c.cc.Delete(ctx, in)
}

func (c *RoleImpl) Get(ctx context.Context, in *SysRole) (*SysRole, error) {
	return c.cc.Get(ctx, in)
}

func (c *RoleImpl) List(ctx context.Context, in *emptypb.Empty) (*ListRole, error) {
	return c.cc.List(ctx, in)
}
