// Code generated by protoc-gen-go-server. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v0.0.1
// source: api/role/role.proto

package role

import (
	context "context"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = grpc.Version

type RoleImpl struct {
	cc RoleClient
}

func NewRoleImpl(conn *grpc.ClientConn) *RoleImpl {
	return &RoleImpl{cc: NewRoleClient(conn)}
}

func (c *RoleImpl) CreateSysRole(ctx context.Context, in *SysRole) (*SysRole, error) {
	return c.cc.CreateSysRole(ctx, in)
}

func (c *RoleImpl) UpdateRole(ctx context.Context, in *SysRole) (*SysRole, error) {
	return c.cc.UpdateRole(ctx, in)
}

func (c *RoleImpl) DeleteRole(ctx context.Context, in *SysRole) (*emptypb.Empty, error) {
	return c.cc.DeleteRole(ctx, in)
}

func (c *RoleImpl) GetRole(ctx context.Context, in *SysRole) (*SysRole, error) {
	return c.cc.GetRole(ctx, in)
}

func (c *RoleImpl) ListRole(ctx context.Context, in *emptypb.Empty) (*ListRoleResp, error) {
	return c.cc.ListRole(ctx, in)
}

func (c *RoleImpl) RolePermissions(ctx context.Context, in *SysRole) (*RoleMenu, error) {
	return c.cc.RolePermissions(ctx, in)
}

func (c *RoleImpl) RolePermissionsPut(ctx context.Context, in *RolePermReq) (*RoleMenu, error) {
	return c.cc.RolePermissionsPut(ctx, in)
}

func (c *RoleImpl) RoleSelect(ctx context.Context, in *emptypb.Empty) (*RoleSelectResp, error) {
	return c.cc.RoleSelect(ctx, in)
}
