// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-atreus/atreus-server/app/interface/internal/conf"
	"github.com/go-atreus/atreus-server/app/interface/internal/data"
	"github.com/go-atreus/atreus-server/app/interface/internal/server"
	"github.com/go-atreus/atreus-server/app/interface/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"go.opentelemetry.io/otel/sdk/trace"
)

// Injectors from wire.go:

// initApp init application.
func initApp(logger log.Logger, tracerProvider *trace.TracerProvider, bootstrap *conf.Bootstrap, auth *conf.Auth) (*kratos.App, func(), error) {
	discovery := data.NewDiscovery()
	adminInterface := service.NewAdminInterface(logger, auth, discovery)
	httpServer := server.NewHTTPServer(adminInterface, logger, auth, bootstrap, tracerProvider)
	grpcServer := server.NewGRPCServer()
	registrar := data.NewRegistrar()
	app := newApp(logger, httpServer, grpcServer, registrar)
	return app, func() {
	}, nil
}
