// Code generated by protoc-gen-go-server. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v0.0.1
// source: api/organization/organization.proto

package organization

import (
	context "context"
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = grpc.Version

type OrganizationImpl struct {
	cc OrganizationClient
}

func NewOrganizationImpl(conn *grpc.ClientConn) *OrganizationImpl {
	return &OrganizationImpl{cc: NewOrganizationClient(conn)}
}

func (c *OrganizationImpl) CreateOrganization(ctx context.Context, in *SysOrganization) (*SysOrganization, error) {
	return c.cc.CreateOrganization(ctx, in)
}

func (c *OrganizationImpl) QueryOrganization(ctx context.Context, in *SysOrganization) (*SysOrganization, error) {
	return c.cc.QueryOrganization(ctx, in)
}

func (c *OrganizationImpl) UpdateOrganization(ctx context.Context, in *SysOrganization) (*SysOrganization, error) {
	return c.cc.UpdateOrganization(ctx, in)
}

func (c *OrganizationImpl) DeleteOrganization(ctx context.Context, in *SysOrganization) (*SysOrganization, error) {
	return c.cc.DeleteOrganization(ctx, in)
}

func (c *OrganizationImpl) ListOrganization(ctx context.Context, in *SysOrganization) (*ListSysOrganization, error) {
	return c.cc.ListOrganization(ctx, in)
}

func (c *OrganizationImpl) OrganizationTree(ctx context.Context, in *SysOrganization) (*ListSysOrganization, error) {
	return c.cc.OrganizationTree(ctx, in)
}
